### ISSUE TITLE
Possibility to specify Dagger Component

### ISSUE THREAD

**Issue by alecarnevale** [alecarnevale/claymore#5]
Claymore automatically installs the module in the `SingletonComponent`.

Evaluate the possibility to specify the component when using annotation.

**Comment by dcampogiani** [comment]
I would love to use this lib, but this issue is a blocker for us!

**Comment by alecarnevale** [comment]
Added in #17 released with version [1.3.0](https://github.com/alecarnevale/claymore/releases/tag/1.3.0).
